"""add user_id to user_tasks

Revision ID: b8719a8d6427
Revises: b01a3f4d8e40
Create Date: 2026-02-27 09:43:09.986734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8719a8d6427'
down_revision: Union[str, Sequence[str], None] = 'b01a3f4d8e40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_user_table_id'), 'user_table', ['id'], unique=False)
    op.add_column('user_tasks', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_user_tasks_id'), 'user_tasks', ['id'], unique=False)
    op.create_foreign_key(None, 'user_tasks', 'user_table', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_tasks', type_='foreignkey')
    op.drop_index(op.f('ix_user_tasks_id'), table_name='user_tasks')
    op.drop_column('user_tasks', 'user_id')
    op.drop_index(op.f('ix_user_table_id'), table_name='user_table')
    # ### end Alembic commands ###
